import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.get

class ConfigAndroidSourceSet : Plugin<Project> by local plugin {
    android {
        sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
        sourceSets["main"].res.srcDir("src/androidMain/res")
    }

    // Remove unused source set generated by AGP on KMP modules that causes build warnings:
    // The Kotlin source set androidAndroidTestRelease was configured but not added to any Kotlin
    // compilation. You can add a source set to a target's compilation by connecting it with the
    // compilation's default source set using 'dependsOn'.
    kotlin {
        sourceSets.apply {
            remove(getByName("androidAndroidTestRelease"))
            remove(getByName("androidTestFixtures"))
            remove(getByName("androidTestFixturesDebug"))
            remove(getByName("androidTestFixturesRelease"))
        }
    }
}
